#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

mkdir -p /home/application
adduser -D -s /bin/bash ${USER}
chown ${USER}:${USER} /home/application

echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

wget https://github.com/tsuru/deploy-agent/releases/download/0.2.5/deploy-agent_0.2.5_linux_amd64.tar.gz
tar zxvf deploy-agent_0.2.5_linux_amd64.tar.gz
mv tsuru_unit_agent /usr/sbin/tsuru_unit_agent
rm deploy-agent_0.2.5_linux_amd64.tar.gz

mkdir -p ${SOURCE_DIR}/default
