#!/bin/sh -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

mkdir -p /home/application

apk update
apk add jq rsync vim curl

wget https://github.com/tsuru/deploy-agent/releases/download/0.2.2/deploy-agent-0.2.2.tar.gz
tar zxvf deploy-agent-0.2.2.tar.gz
mv deploy-agent /usr/sbin
rm deploy-agent-0.2.2.tar.gz

mkdir -p ${SOURCE_DIR}/default
